spring:
  application:
    name: mongodb
  data:
    mongodb:
      host: localhost
      port: 27017
      database: spring_mongo
      username: root
      password: password
      authentication-database: admin
