# Use root/example as user/password credentials
version: '3.8'

services:

  mongo:
    container_name: spring-mongo
    image: mongo:7.0.14-jammy
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  mongo-express:
    container_name: spring-mongo-express
    image: mongo-express:1.0.2-20-alpine3.19
    depends_on:
      - mongo
    ports:
      - 28017:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: spring-mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
